### ISSUE TITLE
Could use PureRenderMixin in the components.

### ISSUE THREAD

**Issue by vasco3** [MandarinConLaBarba/flux-immutable-todomvc#1]
Thanks for the example, it is very well elaborated and helpful. 
I think this is a perfect opportunity to add the PurRenderMixin or at least shouldComponentUpdate.

**Comment by MandarinConLaBarba** [comment]
Ah good point!

**Comment by MandarinConLaBarba** [comment]
@vasco3 this is done and deployed. Thanks for the tip!

**Comment by vasco3** [comment]
:+1:
