### ISSUE TITLE
No gulpfile

### ISSUE THREAD

**Issue by wmertens** [MandarinConLaBarba/flux-immutable-todomvc#2]
Subject says it all :smile:.

**Comment by MandarinConLaBarba** [comment]
Yeah I didn't add it because it doesn't work well right now...you have to compile and bundle in two steps!

**Comment by vasco3** [comment]
why use gulp instead of pure npm?

**Comment by MandarinConLaBarba** [comment]
I typically don't use browserify cli, so not familiar with it. But yeah I think you could get by w/o gulp here.
